/// ISO 3166-1 alpha-2 country codes → full country names.
///
/// Includes all 37 countries present in the artist_nationalities.json dataset.
const Map<String, String> countryNames = {
  'AR': 'Argentina',
  'AU': 'Australia',
  'BB': 'Barbados',
  'BE': 'Belgium',
  'BR': 'Brazil',
  'CA': 'Canada',
  'CI': 'Ivory Coast',
  'CO': 'Colombia',
  'DE': 'Germany',
  'ES': 'Spain',
  'FR': 'France',
  'GB': 'United Kingdom',
  'GH': 'Ghana',
  'HK': 'Hong Kong',
  'ID': 'Indonesia',
  'IE': 'Ireland',
  'IN': 'India',
  'IS': 'Iceland',
  'IT': 'Italy',
  'JM': 'Jamaica',
  'JP': 'Japan',
  'KE': 'Kenya',
  'KR': 'South Korea',
  'MX': 'Mexico',
  'NG': 'Nigeria',
  'NL': 'Netherlands',
  'NO': 'Norway',
  'PH': 'Philippines',
  'PR': 'Puerto Rico',
  'SE': 'Sweden',
  'SN': 'Senegal',
  'TH': 'Thailand',
  'TT': 'Trinidad & Tobago',
  'TW': 'Taiwan',
  'TZ': 'Tanzania',
  'US': 'United States',
  'ZA': 'South Africa',
};
